version: '3'
services:
  web:
    build: .
    command: >
      bash -c 'bundle exec jekyll serve --force_polling --host=0.0.0.0'
    volumes:
      - .:/takkii.github.io
      - bundle:/usr/local/bundle
    ports:
      - 4000:4000

volumes:
  bundle: